export enum ChessPiece {
    WHITE_KING = 'WHITE_KING',
    WHITE_QUEEN = 'WHITE_QUEEN',
    WHITE_ROOK = 'WHITE_ROOK',
    WHITE_BISHOP = 'WHITE_BISHOP',
    WHITE_KNIGHT = 'WHITE_KNIGHT',
    WHITE_PAWN = 'WHITE_PAWN',
    BLACK_KING = 'BLACK_KING',
    BLACK_QUEEN = 'BLACK_QUEEN',
    BLACK_ROOK = 'BLACK_ROOK',
    BLACK_BISHOP = 'BLACK_BISHOP',
    BLACK_KNIGHT = 'BLACK_KNIGHT',
    BLACK_PAWN = 'BLACK_PAWN',
}